#!/bin/bash
# Skript kontrollib 20 esimese täisarvu kohta, kas need on algarvud

for ((num=1; num<=20; num++)); do
    if [ $num -lt 2 ]; then
        echo "$num - ei ole algarv"
        continue
    fi

    is_prime=1
    for ((jagaja=2; jagaja<num; jagaja++)); do
        if (( num % jagaja == 0 )); then
            is_prime=0
            break
        fi
    done

    if [ $is_prime -eq 1 ]; then
        echo "$num - on algarv"
    else
        echo "$num - ei ole algarv"
    fi
done
