#!/bin/bash
# Skript tuvastab süsteemi kellaaja ja tervitab kasutajat nimepidi

kasutaja=$USER
aeg=$(date +%H)

if test $aeg -ge 6 -a $aeg -lt 12
then
    echo "Tere hommikust, $kasutaja!"
elif test $aeg -ge 12 -a $aeg -lt 18
then
    echo "Tere päevast, $kasutaja!"
elif test $aeg -ge 18 -a $aeg -lt 22
then
    echo "Tere õhtust, $kasutaja!"
elif test $aeg -ge 22 -o $aeg -lt 6
then
    echo "Head ööd, $kasutaja!"
else
    echo "Vigane sisend!"
fi

