#!/bin/bash

echo -n "$kasutajanimeEsimeseTaht"
echo "Tere, $kasutajanimeEsimenetaht"
 echo "Tere, $kasutajanimeEsimeneTaht"
kasutajanimeYlejaanudOsa=´whoami´ | cut -c2-
echo kasutajanimeYlejaanudOsa
echo $kasutajanimeYlejaanudOsa
echo "Tere, $kasutajanimeEsimeneTaht$kasutajanimeYlejaanudOsa!"
kasutajanimeYlejaanudOsa=´whoami´ | cut -c2-

